# Generated by Django 5.2.8 on 2025-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='base_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
